// 19_exception_unwind.c - Decompiled from stbc.exe
// Generated by ghidra_export_decompiled.java (merged symbols)


// ====== 0x008700e8  FUN_008700e8 ======

uint FUN_008700e8(uint param_1)

{
  byte bVar1;
  uint uVar2;
  undefined4 *puVar3;
  HANDLE hTargetProcessHandle;
  HANDLE hSourceHandle;
  HANDLE hSourceProcessHandle;
  int iVar4;
  HANDLE *lpTargetHandle;
  DWORD DVar5;
  BOOL BVar6;
  DWORD dwOptions;
  HANDLE local_8;
  
  if (param_1 < DAT_009b4100) {
    iVar4 = (param_1 & 0x1f) * 0x24;
    if ((*(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar4) & 1) != 0) {
      FUN_008680cf(param_1);
      bVar1 = *(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar4);
      uVar2 = FUN_00867dc8();
      if (uVar2 == 0xffffffff) {
        puVar3 = (undefined4 *)FUN_0085cbd7();
        *puVar3 = 0x18;
        puVar3 = (undefined4 *)FUN_0085cbe0();
        *puVar3 = 0;
        FUN_0086812e(param_1);
        return 0xffffffff;
      }
      dwOptions = 2;
      BVar6 = 1;
      lpTargetHandle = &local_8;
      DVar5 = 0;
      hTargetProcessHandle = GetCurrentProcess();
      hSourceHandle = (HANDLE)FUN_00867fe6(param_1);
      hSourceProcessHandle = GetCurrentProcess();
      BVar6 = DuplicateHandle(hSourceProcessHandle,hSourceHandle,hTargetProcessHandle,lpTargetHandle
                              ,DVar5,BVar6,dwOptions);
      if (BVar6 == 0) {
        DVar5 = GetLastError();
      }
      else {
        FUN_00867eeb(uVar2,local_8);
        DVar5 = 0;
      }
      FUN_0086812e(uVar2);
      FUN_0086812e(param_1);
      if (DVar5 != 0) {
        FUN_0085cb64(DVar5);
        return 0xffffffff;
      }
      *(byte *)((&DAT_009b4000)[(int)uVar2 >> 5] + 4 + (uVar2 & 0x1f) * 0x24) = bVar1 & 0xef;
      return uVar2;
    }
  }
  puVar3 = (undefined4 *)FUN_0085cbd7();
  *puVar3 = 9;
  puVar3 = (undefined4 *)FUN_0085cbe0();
  *puVar3 = 0;
  return 0xffffffff;
}


// ====== 0x008701f0  FUN_008701f0 ======

undefined4 FUN_008701f0(uint param_1,uint param_2)

{
  int iVar1;
  undefined4 *puVar2;
  HANDLE hTargetProcessHandle;
  HANDLE hSourceHandle;
  HANDLE hSourceProcessHandle;
  HANDLE in_ECX;
  int iVar3;
  undefined4 uVar4;
  HANDLE *lpTargetHandle;
  DWORD DVar5;
  uint uVar6;
  BOOL BVar7;
  DWORD dwOptions;
  HANDLE local_8;
  
  if (DAT_009b4100 <= param_1) goto LAB_00870291;
  iVar3 = (param_1 & 0x1f) * 0x24;
  if (((*(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar3) & 1) == 0) || (0x7ff < param_2))
  goto LAB_00870291;
  local_8 = in_ECX;
  if (((int)DAT_009b4100 <= (int)param_2) && (iVar1 = FUN_00870361(param_2), iVar1 != 0)) {
    puVar2 = (undefined4 *)FUN_0085cbd7();
    *puVar2 = 0xc;
    return 0xffffffff;
  }
  if ((int)param_1 < (int)param_2) {
    FUN_008680cf(param_1);
    uVar6 = param_2;
LAB_00870271:
    FUN_008680cf(uVar6);
  }
  else if ((int)param_2 < (int)param_1) {
    FUN_008680cf(param_2);
    uVar6 = param_1;
    goto LAB_00870271;
  }
  if ((*(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar3) & 1) != 0) {
    if (param_1 == param_2) {
      uVar4 = 0;
    }
    else {
      iVar1 = (param_2 & 0x1f) * 0x24;
      if ((*(byte *)((&DAT_009b4000)[(int)param_2 >> 5] + 4 + iVar1) & 1) != 0) {
        FUN_0086398d(param_2);
      }
      dwOptions = 2;
      BVar7 = 1;
      lpTargetHandle = &local_8;
      DVar5 = 0;
      hTargetProcessHandle = GetCurrentProcess();
      hSourceHandle = (HANDLE)FUN_00867fe6(param_1);
      hSourceProcessHandle = GetCurrentProcess();
      BVar7 = DuplicateHandle(hSourceProcessHandle,hSourceHandle,hTargetProcessHandle,lpTargetHandle
                              ,DVar5,BVar7,dwOptions);
      if (BVar7 == 0) {
        DVar5 = GetLastError();
      }
      else {
        FUN_00867eeb(param_2,local_8);
        DVar5 = 0;
      }
      if (DVar5 == 0) {
        uVar4 = 0;
        *(byte *)((&DAT_009b4000)[(int)param_2 >> 5] + 4 + iVar1) =
             *(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar3) & 0xef;
      }
      else {
        FUN_0085cb64(DVar5);
        uVar4 = 0xffffffff;
      }
    }
    FUN_0086812e(param_1);
    FUN_0086812e(param_2);
    return uVar4;
  }
  FUN_0086812e(param_1);
  FUN_0086812e(param_2);
LAB_00870291:
  puVar2 = (undefined4 *)FUN_0085cbd7();
  *puVar2 = 9;
  puVar2 = (undefined4 *)FUN_0085cbe0();
  *puVar2 = 0;
  return 0xffffffff;
}


// ====== 0x00870361  FUN_00870361 ======

undefined4 FUN_00870361(int param_1)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  int *piVar3;
  
  if (DAT_009b4100 <= param_1) {
    piVar3 = &DAT_009b4000;
    do {
      if (*piVar3 == 0) {
        puVar2 = _malloc(0x480);
        if (puVar2 == (undefined4 *)0x0) {
          return 0xffffffff;
        }
        DAT_009b4100 = DAT_009b4100 + 0x20;
        *piVar3 = (int)puVar2;
        puVar1 = puVar2;
        for (; puVar2 < puVar1 + 0x120; puVar2 = puVar2 + 9) {
          *(undefined1 *)(puVar2 + 1) = 0;
          *puVar2 = 0xffffffff;
          puVar2[2] = 0;
          *(undefined1 *)((int)puVar2 + 5) = 10;
          puVar1 = (undefined4 *)*piVar3;
        }
      }
      piVar3 = piVar3 + 1;
    } while (DAT_009b4100 <= param_1);
  }
  return 0;
}


// ====== 0x008703cb  FUN_008703cb ======

undefined4 FUN_008703cb(uint param_1,uint *param_2)

{
  int *piVar1;
  uint *puVar2;
  DWORD DVar3;
  undefined4 *puVar4;
  BOOL BVar5;
  uint uVar6;
  int iVar7;
  _BY_HANDLE_FILE_INFORMATION local_54;
  _SYSTEMTIME local_20;
  _FILETIME local_10;
  undefined4 local_8;
  
  local_8 = 0;
  if (DAT_009b4100 <= param_1) {
LAB_0087064c:
    puVar4 = (undefined4 *)FUN_0085cbd7();
    *puVar4 = 9;
    return 0xffffffff;
  }
  piVar1 = &DAT_009b4000 + ((int)param_1 >> 5);
  iVar7 = (param_1 & 0x1f) * 0x24;
  if ((*(byte *)(*piVar1 + 4 + iVar7) & 1) == 0) goto LAB_0087064c;
  FUN_008680cf(param_1);
  DVar3 = GetFileType(*(HANDLE *)(*piVar1 + iVar7));
  puVar2 = param_2;
  uVar6 = DVar3 & 0xffff7fff;
  if (uVar6 != 1) {
    if (uVar6 == 2) {
      *(undefined2 *)((int)param_2 + 6) = 0x2000;
    }
    else {
      if (uVar6 != 3) {
        if (uVar6 == 0) {
          puVar4 = (undefined4 *)FUN_0085cbd7();
          *puVar4 = 9;
          goto LAB_00870446;
        }
        goto LAB_008704f2;
      }
      *(undefined2 *)((int)param_2 + 6) = 0x1000;
    }
    *(undefined2 *)(param_2 + 2) = 1;
    *param_2 = param_1;
    param_2[4] = param_1;
    *(undefined2 *)(param_2 + 1) = 0;
    *(undefined2 *)(param_2 + 3) = 0;
    *(undefined2 *)((int)param_2 + 10) = 0;
    param_2[8] = 0;
    param_2[7] = 0;
    param_2[6] = 0;
    if (uVar6 == 2) {
      param_2[5] = 0;
    }
    else {
      BVar5 = PeekNamedPipe(*(HANDLE *)(*piVar1 + iVar7),(LPVOID)0x0,0,(LPDWORD)0x0,
                            (LPDWORD)&param_2,(LPDWORD)0x0);
      if (BVar5 == 0) {
        puVar2[5] = 0;
      }
      else {
        puVar2[5] = (uint)param_2;
      }
    }
    goto LAB_0087044a;
  }
  *(undefined2 *)((int)param_2 + 6) = 0;
  *(undefined2 *)(param_2 + 3) = 0;
  *(undefined2 *)((int)param_2 + 10) = 0;
  *(undefined2 *)(param_2 + 1) = 0;
  *(undefined2 *)(param_2 + 2) = 1;
  BVar5 = GetFileInformationByHandle(*(HANDLE *)(*piVar1 + iVar7),&local_54);
  if (BVar5 == 0) {
LAB_008704f2:
    DVar3 = GetLastError();
    FUN_0085cb64(DVar3);
  }
  else {
    if (((byte)local_54.dwFileAttributes & 1) == 0) {
      *(ushort *)((int)puVar2 + 6) = *(ushort *)((int)puVar2 + 6) | 0x1b6;
    }
    else {
      *(ushort *)((int)puVar2 + 6) = *(ushort *)((int)puVar2 + 6) | 0x124;
    }
    BVar5 = FileTimeToLocalFileTime(&local_54.ftLastWriteTime,&local_10);
    if ((BVar5 != 0) && (BVar5 = FileTimeToSystemTime(&local_10,&local_20), BVar5 != 0)) {
      uVar6 = FUN_008679d8(local_20.wYear,local_20.wMonth,local_20.wDay,local_20.wHour,
                           local_20.wMinute,local_20.wSecond,0xffffffff);
      puVar2[7] = uVar6;
      if ((local_54.ftLastAccessTime.dwLowDateTime == 0) &&
         (local_54.ftLastAccessTime.dwHighDateTime == 0)) {
LAB_008705d0:
        puVar2[6] = uVar6;
        if ((local_54.ftCreationTime.dwLowDateTime == 0) &&
           (local_54.ftCreationTime.dwHighDateTime == 0)) {
          uVar6 = puVar2[7];
        }
        else {
          BVar5 = FileTimeToLocalFileTime(&local_54.ftCreationTime,&local_10);
          if ((BVar5 == 0) || (BVar5 = FileTimeToSystemTime(&local_10,&local_20), BVar5 == 0))
          goto LAB_00870644;
          uVar6 = FUN_008679d8(local_20.wYear,local_20.wMonth,local_20.wDay,local_20.wHour,
                               local_20.wMinute,local_20.wSecond,0xffffffff);
        }
        *(byte *)((int)puVar2 + 7) = *(byte *)((int)puVar2 + 7) | 0x80;
        puVar2[8] = uVar6;
        *puVar2 = 0;
        puVar2[5] = local_54.nFileSizeLow;
        puVar2[4] = 0;
      }
      else {
        BVar5 = FileTimeToLocalFileTime(&local_54.ftLastAccessTime,&local_10);
        if ((BVar5 != 0) && (BVar5 = FileTimeToSystemTime(&local_10,&local_20), BVar5 != 0)) {
          uVar6 = FUN_008679d8(local_20.wYear,local_20.wMonth,local_20.wDay,local_20.wHour,
                               local_20.wMinute,local_20.wSecond,0xffffffff);
          goto LAB_008705d0;
        }
LAB_00870644:
        local_8 = 0xffffffff;
      }
      goto LAB_0087044a;
    }
  }
LAB_00870446:
  local_8 = 0xffffffff;
LAB_0087044a:
  FUN_0086812e(param_1);
  return local_8;
}


// ====== 0x0087065e  FUN_0087065e ======

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

int FUN_0087065e(uint param_1,char *param_2)

{
  char cVar1;
  bool bVar2;
  bool bVar3;
  bool bVar4;
  bool bVar5;
  bool bVar6;
  int iVar7;
  
  if (((DAT_009b4100 <= param_1) ||
      (bVar3 = true,
      (*(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + (param_1 & 0x1f) * 0x24) & 1) == 0)) ||
     (iVar7 = FUN_00863bab(), iVar7 == 0)) {
    return 0;
  }
  cVar1 = *param_2;
  if (cVar1 != 'a') {
    if (cVar1 == 'r') {
      *(undefined4 *)(iVar7 + 0xc) = 1;
      goto LAB_008706c4;
    }
    if (cVar1 != 'w') {
      iVar7 = 0;
      goto LAB_00870740;
    }
  }
  *(undefined4 *)(iVar7 + 0xc) = 2;
LAB_008706c4:
  *(uint *)(iVar7 + 0xc) = *(uint *)(iVar7 + 0xc) | DAT_009b3cd8;
  bVar2 = bVar3;
  bVar4 = false;
  bVar6 = false;
LAB_008706d4:
  bVar5 = bVar6;
  cVar1 = param_2[1];
  param_2 = param_2 + 1;
  if ((cVar1 == '\0') || (!bVar2)) goto LAB_00870733;
  bVar6 = bVar5;
  if (cVar1 == '+') {
    if ((*(uint *)(iVar7 + 0xc) & 0x80) == 0) {
      *(uint *)(iVar7 + 0xc) = *(uint *)(iVar7 + 0xc) & 0xfffffffc | 0x80;
      goto LAB_008706d4;
    }
  }
  else {
    if (cVar1 == 'b') {
LAB_00870714:
      bVar6 = bVar3;
      if (bVar5) goto LAB_00870726;
      goto LAB_008706d4;
    }
    if (cVar1 == 'c') {
      if (bVar4) goto LAB_00870726;
      *(byte *)(iVar7 + 0xd) = *(byte *)(iVar7 + 0xd) | 0x40;
      bVar4 = bVar3;
      goto LAB_008706d4;
    }
    if (cVar1 == 'n') {
      if (bVar4) goto LAB_00870726;
      *(byte *)(iVar7 + 0xd) = *(byte *)(iVar7 + 0xd) & 0xbf;
      bVar4 = bVar3;
      goto LAB_008706d4;
    }
    if (cVar1 == 't') goto LAB_00870714;
  }
LAB_00870726:
  bVar2 = false;
  bVar6 = bVar5;
  goto LAB_008706d4;
LAB_00870733:
  _DAT_009b3968 = _DAT_009b3968 + 1;
  *(uint *)(iVar7 + 0x10) = param_1;
LAB_00870740:
  FUN_0085bfc5(iVar7);
  return iVar7;
}


// ====== 0x00870751  GetCurrentProcessId ======

/* category=engine_internal */

DWORD GetCurrentProcessId(void)

{
  DWORD DVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00870751. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  DVar1 = GetCurrentProcessId();
  return DVar1;
}


// ====== 0x00870757  FUN_00870757 ======

void FUN_00870757(char *param_1,char *param_2,char *param_3,char *param_4,char *param_5)

{
  char cVar1;
  char *pcVar2;
  char *pcVar3;
  
  if ((param_2 != (char *)0x0) && (*param_2 != '\0')) {
    *param_1 = *param_2;
    param_1[1] = ':';
    param_1 = param_1 + 2;
  }
  if ((param_3 != (char *)0x0) && (cVar1 = *param_3, pcVar2 = param_3, cVar1 != '\0')) {
    do {
      pcVar3 = param_1;
      *pcVar3 = cVar1;
      cVar1 = pcVar2[1];
      param_1 = pcVar3 + 1;
      pcVar2 = pcVar2 + 1;
    } while (cVar1 != '\0');
    pcVar2 = (char *)FUN_00870cd7(param_3,pcVar2);
    if ((*pcVar2 != '/') && (*pcVar2 != '\\')) {
      *param_1 = '\\';
      param_1 = pcVar3 + 2;
    }
  }
  if (param_4 != (char *)0x0) {
    cVar1 = *param_4;
    while (cVar1 != '\0') {
      *param_1 = cVar1;
      pcVar2 = param_4 + 1;
      param_1 = param_1 + 1;
      param_4 = param_4 + 1;
      cVar1 = *pcVar2;
    }
  }
  if (param_5 == (char *)0x0) {
    *param_1 = '\0';
  }
  else {
    if ((*param_5 != '\0') && (*param_5 != '.')) {
      *param_1 = '.';
      param_1 = param_1 + 1;
    }
    do {
      cVar1 = *param_5;
      *param_1 = cVar1;
      param_1 = param_1 + 1;
      param_5 = param_5 + 1;
    } while (cVar1 != '\0');
  }
  return;
}


// ====== 0x008707e8  FUN_008707e8 ======

uint FUN_008707e8(uint param_1)

{
  undefined2 uVar1;
  uint uVar2;
  undefined2 extraout_var;
  LONG LVar3;
  undefined2 uVar4;
  ushort uVar5;
  bool bVar6;
  
  uVar2 = 0xffff;
  uVar5 = (ushort)param_1;
  if (uVar5 != 0xffff) {
    if (DAT_009b3a68 == 0) {
      if ((0x40 < uVar5) && (uVar5 < 0x5b)) {
        param_1 = param_1 + 0x20;
      }
      uVar2 = param_1 & 0xffff;
    }
    else {
      InterlockedIncrement(&DAT_009b4334);
      bVar6 = DAT_009b4330 != 0;
      if (bVar6) {
        InterlockedDecrement(&DAT_009b4334);
        FUN_00860a61(0x13);
      }
      uVar1 = FUN_00870862(param_1);
      if (bVar6) {
        FUN_00860ac2(0x13);
        uVar4 = extraout_var;
      }
      else {
        LVar3 = InterlockedDecrement(&DAT_009b4334);
        uVar4 = (short)((uint)LVar3 >> 0x10);
      }
      uVar2 = CONCAT22(uVar4,uVar1);
    }
  }
  return uVar2;
}


// ====== 0x00870862  FUN_00870862 ======

uint FUN_00870862(uint param_1)

{
  ushort uVar1;
  int iVar2;
  ushort local_6;
  
  uVar1 = (ushort)param_1;
  if (uVar1 == 0xffff) {
    return param_1;
  }
  if (DAT_009b3a68 == 0) {
    if ((0x40 < uVar1) && (uVar1 < 0x5b)) {
      return param_1 + 0x20;
    }
  }
  else {
    if (uVar1 < 0x100) {
      iVar2 = FUN_00868be8(param_1,1);
      if (iVar2 == 0) {
        return param_1 & 0xffff;
      }
    }
    iVar2 = FUN_00870d44(DAT_009b3a68,0x100,&param_1,1,&local_6,1,0);
    param_1 = param_1 & 0xffff;
    if (iVar2 != 0) {
      param_1 = (uint)local_6;
    }
  }
  return param_1;
}


// ====== 0x008708d7  FUN_008708d7 ======

int FUN_008708d7(byte *param_1,byte *param_2)

{
  byte *pbVar1;
  int iVar2;
  uint uVar3;
  byte *pbVar4;
  ushort uVar5;
  ushort uVar6;
  uint uVar7;
  byte *local_10;
  byte *local_c;
  byte local_8;
  byte local_7;
  
  if (DAT_009b411c == 0) {
    iVar2 = FUN_0085b2b0(param_1,param_2);
  }
  else {
    FUN_00860a61(0x19);
    local_10 = param_2 + -1;
    local_c = param_1 + -1;
    do {
      uVar7 = (uint)*param_1;
      pbVar4 = param_1 + 1;
      pbVar1 = local_c + 1;
      if ((*(byte *)((int)&DAT_009b4220 + uVar7 + 1) & 4) == 0) {
        param_1 = pbVar4;
        local_c = pbVar1;
        if ((*(byte *)((int)&DAT_009b4220 + uVar7 + 1) & 0x10) == 0x10) {
          uVar7 = (uint)(byte)(&DAT_009b4120)[uVar7];
        }
      }
      else if (*pbVar4 == 0) {
        uVar7 = 0;
        param_1 = pbVar4;
        local_c = pbVar1;
      }
      else {
        iVar2 = FUN_00867640(DAT_009b4324,0x200,pbVar1,2,&local_8,2,DAT_009b4104,1);
        if (iVar2 == 1) {
          uVar7 = (uint)local_8;
        }
        else {
          if (iVar2 != 2) goto LAB_00870a3b;
          uVar7 = (uint)local_8 * 0x100 + (uint)local_7;
        }
        param_1 = param_1 + 2;
        local_c = local_c + 2;
      }
      uVar3 = (uint)*param_2;
      uVar5 = (ushort)*param_2;
      pbVar4 = param_2 + 1;
      pbVar1 = local_10 + 1;
      if ((*(byte *)((int)&DAT_009b4220 + uVar3 + 1) & 4) == 0) {
        param_2 = pbVar4;
        local_10 = pbVar1;
        if ((*(byte *)((int)&DAT_009b4220 + uVar3 + 1) & 0x10) == 0x10) {
          uVar5 = (ushort)(byte)(&DAT_009b4120)[uVar3];
        }
      }
      else if (*pbVar4 == 0) {
        uVar5 = 0;
        param_2 = pbVar4;
        local_10 = pbVar1;
      }
      else {
        iVar2 = FUN_00867640(DAT_009b4324,0x200,pbVar1,2,&local_8,2,DAT_009b4104,1);
        if (iVar2 == 1) {
          uVar5 = (ushort)local_8;
        }
        else {
          if (iVar2 != 2) {
LAB_00870a3b:
            FUN_00860ac2(0x19);
            return 0x7fffffff;
          }
          uVar5 = (ushort)local_8 * 0x100 + (ushort)local_7;
        }
        param_2 = param_2 + 2;
        local_10 = local_10 + 2;
      }
      uVar6 = (ushort)uVar7;
      if (uVar6 != uVar5) {
        FUN_00860ac2(0x19);
        return (-(uint)(uVar5 < uVar6) & 2) - 1;
      }
    } while (uVar6 != 0);
    FUN_00860ac2(0x19);
    iVar2 = 0;
  }
  return iVar2;
}


// ====== 0x00870a6c  FUN_00870a6c ======

LPSTR FUN_00870a6c(LPSTR param_1,LPCSTR param_2,DWORD param_3)

{
  LPCSTR lpFileName;
  LPSTR pCVar1;
  undefined4 *puVar2;
  DWORD DVar3;
  
  lpFileName = param_2;
  if ((param_2 != (LPCSTR)0x0) && (*param_2 != '\0')) {
    pCVar1 = param_1;
    if (param_1 == (LPSTR)0x0) {
      pCVar1 = _malloc(0x104);
      if (pCVar1 == (LPSTR)0x0) {
        puVar2 = (undefined4 *)FUN_0085cbd7();
        *puVar2 = 0xc;
        return (LPSTR)0x0;
      }
      param_3 = 0x104;
    }
    DVar3 = GetFullPathNameA(lpFileName,param_3,pCVar1,&param_2);
    if (DVar3 < param_3) {
      if (DVar3 != 0) {
        return pCVar1;
      }
      if (param_1 == (LPSTR)0x0) {
        FUN_0085adc4(pCVar1);
      }
      DVar3 = GetLastError();
      FUN_0085cb64(DVar3);
    }
    else {
      if (param_1 == (LPSTR)0x0) {
        FUN_0085adc4(pCVar1);
      }
      puVar2 = (undefined4 *)FUN_0085cbd7();
      *puVar2 = 0x22;
    }
    return (LPSTR)0x0;
  }
  pCVar1 = (LPSTR)FUN_00859eeb(param_1,param_3);
  return pCVar1;
}


// ====== 0x00870b11  FUN_00870b11 ======

int FUN_00870b11(void)

{
  DWORD DVar1;
  int iVar2;
  CHAR local_108;
  char local_107;
  
  iVar2 = 0;
  DVar1 = GetCurrentDirectoryA(0x104,&local_108);
  if ((DVar1 != 0) && (local_107 == ':')) {
    iVar2 = FUN_0085e89f(local_108);
    iVar2 = iVar2 + -0x40;
  }
  return iVar2;
}


// ====== 0x00870b54  FUN_00870b54 ======

undefined4 FUN_00870b54(uint param_1)

{
  uint uVar1;
  int iVar2;
  BOOL BVar3;
  DWORD DVar4;
  undefined4 *puVar5;
  undefined4 uVar6;
  
  iVar2 = param_1;
  if (((int)param_1 < 1) || (0x1f < (int)param_1)) {
    puVar5 = (undefined4 *)FUN_0085cbd7();
    *puVar5 = 0xd;
    puVar5 = (undefined4 *)FUN_0085cbe0();
    *puVar5 = 0xf;
    uVar6 = 0xffffffff;
  }
  else {
    FUN_00860a61(0xc);
    uVar1 = param_1 >> 0x10;
    param_1._0_2_ = CONCAT11(0x3a,(char)iVar2 + '@');
    param_1 = CONCAT22((short)uVar1,(undefined2)param_1) & 0xff00ffff;
    BVar3 = SetCurrentDirectoryA((LPCSTR)&param_1);
    if (BVar3 == 0) {
      DVar4 = GetLastError();
      FUN_0085cb64(DVar4);
      uVar6 = 0xffffffff;
    }
    else {
      uVar6 = 0;
    }
    FUN_00860ac2(0xc);
  }
  return uVar6;
}


// ====== 0x00870bc7  FUN_00870bc7 ======

uint FUN_00870bc7(uint param_1)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  uint uVar4;
  undefined1 uVar5;
  undefined2 local_8;
  
  uVar4 = param_1;
  if (param_1 < 0x100) {
    if ((*(byte *)((int)&DAT_009b4220 + param_1 + 1) & 0x10) == 0x10) {
      uVar4 = (uint)(byte)(&DAT_009b4120)[param_1];
    }
  }
  else {
    uVar5 = (undefined1)param_1;
    uVar2 = param_1 >> 8;
    uVar1 = param_1 >> 8;
    param_1 = CONCAT13(uVar5,CONCAT12((char)uVar1,(undefined2)param_1));
    if (((*(byte *)((int)&DAT_009b4220 + (uVar2 & 0xff) + 1) & 4) != 0) &&
       (iVar3 = FUN_00867640(DAT_009b4324,0x100,(int)&param_1 + 2,2,&local_8,2,DAT_009b4104,1),
       iVar3 != 0)) {
      uVar4 = (uint)CONCAT11((undefined1)local_8,local_8._1_1_);
    }
  }
  return uVar4;
}


// ====== 0x00870c42  FUN_00870c42 ======

uint FUN_00870c42(byte *param_1,byte *param_2)

{
  byte bVar1;
  uint uVar2;
  byte *pbVar3;
  byte *pbVar4;
  
  if (DAT_009b411c == 0) {
    uVar2 = FUN_00869f70(param_1,param_2);
    return uVar2;
  }
  FUN_00860a61(0x19);
  bVar1 = *param_1;
  while (bVar1 != 0) {
    bVar1 = *param_2;
    pbVar3 = param_2;
    while (bVar1 != 0) {
      bVar1 = *pbVar3;
      if ((*(byte *)((int)&DAT_009b4220 + bVar1 + 1) & 4) == 0) {
        pbVar4 = pbVar3;
        if (bVar1 == *param_1) break;
      }
      else if (((bVar1 == *param_1) && (pbVar3[1] == param_1[1])) ||
              (pbVar4 = pbVar3 + 1, pbVar3[1] == 0)) break;
      pbVar3 = pbVar4 + 1;
      bVar1 = *pbVar3;
    }
    if ((*pbVar3 != 0) ||
       (((*(byte *)((int)&DAT_009b4220 + *param_1 + 1) & 4) != 0 &&
        (param_1 = param_1 + 1, *param_1 == 0)))) break;
    param_1 = param_1 + 1;
    bVar1 = *param_1;
  }
  FUN_00860ac2(0x19);
  return -(uint)(*param_1 != 0) & (uint)param_1;
}


// ====== 0x00870cd7  FUN_00870cd7 ======

byte * FUN_00870cd7(byte *param_1,byte *param_2)

{
  byte *pbVar1;
  
  if (param_1 < param_2) {
    if (DAT_009b411c == 0) {
      param_2 = param_2 + -1;
    }
    else {
      FUN_00860a61(0x19);
      pbVar1 = param_2 + -1;
      if ((*(byte *)((int)&DAT_009b4220 + param_2[-1] + 1) & 4) == 0) {
        do {
          pbVar1 = pbVar1 + -1;
          if (pbVar1 < param_1) break;
        } while ((*(byte *)((int)&DAT_009b4220 + *pbVar1 + 1) & 4) != 0);
        FUN_00860ac2(0x19);
        param_2 = param_2 + (-1 - ((int)param_2 - (int)pbVar1 & 1U));
      }
      else {
        FUN_00860ac2(0x19);
        param_2 = param_2 + -2;
      }
    }
  }
  else {
    param_2 = (byte *)0x0;
  }
  return param_2;
}


// ====== 0x00870d44  FUN_00870d44 ======

size_t FUN_00870d44(LCID param_1,uint param_2,LPCWSTR param_3,int param_4,LPWSTR param_5,
                   size_t param_6,UINT param_7)

{
  int iVar1;
  size_t sVar2;
  int iVar3;
  void *local_14;
  undefined1 *puStack_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &DAT_0089df68;
  puStack_10 = &LAB_0085fed0;
  local_14 = ExceptionList;
  ExceptionList = &local_14;
  if (DAT_009b3e30 == 0) {
    ExceptionList = &local_14;
    iVar1 = LCMapStringW(0,0x100,L"",1,(LPWSTR)0x0,0);
    if (iVar1 == 0) {
      iVar1 = LCMapStringA(0,0x100,"",1,(LPSTR)0x0,0);
      if (iVar1 == 0) {
        ExceptionList = local_14;
        return 0;
      }
      DAT_009b3e30 = 2;
    }
    else {
      DAT_009b3e30 = 1;
    }
  }
  if (0 < param_4) {
    param_4 = FUN_00870f4d(param_3,param_4);
  }
  if (DAT_009b3e30 == 1) {
    sVar2 = LCMapStringW(param_1,param_2,param_3,param_4,param_5,param_6);
    ExceptionList = local_14;
    return sVar2;
  }
  if (DAT_009b3e30 == 2) {
    if (param_7 == 0) {
      param_7 = DAT_009b3a78;
    }
    iVar1 = WideCharToMultiByte(param_7,0x220,param_3,param_4,(LPSTR)0x0,0,(LPCSTR)0x0,(LPBOOL)0x0);
    if (iVar1 != 0) {
      local_8 = 0;
      FUN_0085f3a0();
      local_8 = 0xffffffff;
      if ((&stack0x00000000 != (undefined1 *)0x3c) &&
         (iVar3 = WideCharToMultiByte(param_7,0x220,param_3,param_4,&stack0xffffffc4,iVar1,
                                      (LPCSTR)0x0,(LPBOOL)0x0), iVar3 != 0)) {
        sVar2 = LCMapStringA(param_1,param_2,&stack0xffffffc4,iVar1,(LPSTR)0x0,0);
        if (sVar2 != 0) {
          local_8 = 1;
          FUN_0085f3a0();
          local_8 = 0xffffffff;
          if ((&stack0x00000000 != (undefined1 *)0x3c) &&
             (iVar1 = LCMapStringA(param_1,param_2,&stack0xffffffc4,iVar1,&stack0xffffffc4,sVar2),
             iVar1 != 0)) {
            if ((param_2 & 0x400) != 0) {
              if (param_6 != 0) {
                if ((int)sVar2 <= (int)param_6) {
                  param_6 = sVar2;
                }
                _strncpy((char *)param_5,&stack0xffffffc4,param_6);
                ExceptionList = local_14;
                return sVar2;
              }
              ExceptionList = local_14;
              return sVar2;
            }
            if (param_6 == 0) {
              param_6 = 0;
              param_5 = (LPWSTR)0x0;
            }
            sVar2 = MultiByteToWideChar(param_7,1,&stack0xffffffc4,sVar2,param_5,param_6);
            if (sVar2 != 0) {
              ExceptionList = local_14;
              return sVar2;
            }
          }
        }
      }
    }
  }
  ExceptionList = local_14;
  return 0;
}


// ====== 0x00870f4d  FUN_00870f4d ======

int FUN_00870f4d(short *param_1,int param_2)

{
  short *psVar1;
  int iVar2;
  
  iVar2 = param_2;
  for (psVar1 = param_1; (iVar2 != 0 && (iVar2 = iVar2 + -1, *psVar1 != 0)); psVar1 = psVar1 + 1) {
  }
  if (*psVar1 != 0) {
    return param_2;
  }
  return (int)psVar1 - (int)param_1 >> 1;
}


