//Decompile every function and write bucketed C files mirroring the existing
//reference/decompiled/ layout (19 address-range subsystem files), but with the
//merged symbol names + the newly-created SWIG/NiRTTI functions included.
//Java version -> runs in stock Ghidra, no Jython/PyGhidra needed.
//@category STBC
//@author STBC-RE
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.LinkedHashMap;
import java.util.Map;

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;

public class ghidra_export_decompiled extends GhidraScript {

    // Output dir default: a FRESH dir so we don't clobber the committed snapshot
    // until you've diffed it. Override by passing a path as script arg[0].
    private static final String OUT_DEFAULT =
        "C:\\Users\\mward\\Documents\\Projects\\STBC-Reverse-Engineering"
      + "\\STBC-Reverse-Engineering\\reference\\decompiled_fresh";

    // Subsystem buckets: {start-of-range, filename}. A function is filed in the
    // last bucket whose start <= its entry point. Derived from the address
    // ranges of the existing reference/decompiled/ files.
    private static final long[] STARTS = {
        0x00401000L, 0x00430000L, 0x00460000L, 0x00500000L, 0x00540000L,
        0x005c0000L, 0x00600000L, 0x00640000L, 0x00690000L, 0x006a0000L,
        0x006b0000L, 0x006c0000L, 0x006d0000L, 0x006e0000L, 0x00700000L,
        0x00780000L, 0x00850000L, 0x00860000L, 0x00870000L
    };
    private static final String[] NAMES = {
        "01_core_engine", "02_utopia_app", "03_game_objects", "04_ui_windows",
        "05_game_mission", "06_physics_collision", "07_audio_input",
        "08_ai_pathfinding", "09_multiplayer_game", "10_netfile_checksums",
        "11_tgnetwork", "12_data_serialization", "13_events_timers",
        "14_gamespy", "15_python_swig", "16_netimmerse", "17_crt_imports",
        "18_data_tables", "19_exception_unwind"
    };

    private int bucketFor(long off) {
        int idx = 0;
        for (int i = 0; i < STARTS.length; i++) {
            if (off >= STARTS[i]) idx = i; else break;
        }
        return idx;
    }

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        File outDir = new File((args != null && args.length >= 1 && !args[0].isEmpty())
                               ? args[0] : OUT_DEFAULT);
        if (!outDir.isDirectory() && !outDir.mkdirs()) {
            println("[ERR] cannot create output dir: " + outDir.getAbsolutePath());
            return;
        }
        println("output -> " + outDir.getAbsolutePath());

        DecompInterface decomp = new DecompInterface();
        decomp.setOptions(new DecompileOptions());
        if (!decomp.openProgram(currentProgram)) {
            println("[ERR] decompiler failed to open program: " + decomp.getLastMessage());
            return;
        }

        // One buffer per bucket, keyed by filename (insertion-ordered).
        Map<String, StringBuilder> bufs = new LinkedHashMap<String, StringBuilder>();
        Map<String, Integer> counts = new LinkedHashMap<String, Integer>();
        for (String n : NAMES) {
            StringBuilder sb = new StringBuilder();
            sb.append("// ").append(n).append(".c - Decompiled from stbc.exe\n");
            sb.append("// Generated by ghidra_export_decompiled.java (merged symbols)\n\n\n");
            bufs.put(n, sb);
            counts.put(n, 0);
        }

        int total = currentProgram.getFunctionManager().getFunctionCount();
        monitor.initialize(total);
        int done = 0, failed = 0;

        FunctionIterator it = currentProgram.getFunctionManager().getFunctions(true);
        while (it.hasNext() && !monitor.isCancelled()) {
            Function f = it.next();
            monitor.incrementProgress(1);
            done++;
            if ((done % 250) == 0) monitor.setMessage("decompiling " + done + "/" + total);

            Address entry = f.getEntryPoint();
            // Only .text functions in our mapped range.
            if (entry.getOffset() < STARTS[0]) continue;
            // Skip MSVC exception-unwind funclets (compiler boilerplate, no RE value).
            String fname = f.getName();
            if (fname.startsWith("Unwind@") || fname.startsWith("Catch@")) continue;
            String bucket = NAMES[bucketFor(entry.getOffset())];

            String cText;
            try {
                DecompileResults res = decomp.decompileFunction(f, 60, monitor);
                if (res != null && res.decompileCompleted()
                        && res.getDecompiledFunction() != null) {
                    cText = res.getDecompiledFunction().getC();
                } else {
                    cText = "// [decompile failed: "
                          + (res == null ? "null" : res.getErrorMessage()) + "]\n";
                    failed++;
                }
            } catch (Exception e) {
                cText = "// [decompile exception: " + e + "]\n";
                failed++;
            }

            StringBuilder sb = bufs.get(bucket);
            sb.append("// ====== 0x").append(entry.toString())
              .append("  ").append(f.getName()).append(" ======\n");
            sb.append(cText).append("\n");
            counts.put(bucket, counts.get(bucket) + 1);
        }

        decomp.dispose();

        // Flush every bucket to disk.
        int written = 0;
        for (Map.Entry<String, StringBuilder> e : bufs.entrySet()) {
            File out = new File(outDir, e.getKey() + ".c");
            BufferedWriter w = new BufferedWriter(new FileWriter(out));
            try {
                w.write(e.getValue().toString());
            } finally {
                w.close();
            }
            written++;
            println(String.format("  %-26s %5d fns", e.getKey() + ".c", counts.get(e.getKey())));
        }

        println("========================================================");
        println("decompilation export complete");
        println("  functions processed : " + done);
        println("  decompile failures  : " + failed);
        println("  files written       : " + written);
        println("  output dir          : " + outDir.getAbsolutePath());
        println("========================================================");
    }
}
